comment cleanup.yml out, fix AWS variable for awscli path

diff --git a/roles/atlassian_aws/templates/launch-config.sh.j2 b/roles/atlassian_aws/templates/launch-config.sh.j2
--- a/roles/atlassian_aws/templates/launch-config.sh.j2
+++ b/roles/atlassian_aws/templates/launch-config.sh.j2
@@ -44,7 +44,14 @@ clusterTagKey=Cluster
 clusterTagValue=$stackName
 
 # Executables
-AWS=/usr/local/bin/aws
+if [[ -f /usr/local/bin/aws ]]; then
+  AWS=/usr/local/bin/aws
+elif [[ -f /usr/bin/aws ]]
+  AWS=/usr/bin/aws
+else
+  log "AWS CLI not found exit 1"
+  exit 1
+fi
 
 # Startup parameter
 initState=$1
